M48
; DRILL file {KiCad 7.0.1-0} date 2023 May 07, Sunday 10:40:27
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-07T10:40:27+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.25Y-2.35
X3.25Y-4.85
X8.4Y-2.35
T2
X8.1Y-2.4
X8.1Y-2.675
T0
M30
